Add script to generate runtime dependencies for each project - first draft
ZOSOpenTools/meta pull request #111
Opened 2023-01-13 19:51 UTC by IgorTodorovskiIBM

2023-01-13 23:06 UTC, MikeFultonDev commented on tools/generate_runtime_dependencies.py
> +# Note: Only run this on z/OS
Can you add a comment that says what the input and output is and what env vars are required?

2023-01-13 23:06 UTC, MikeFultonDev requested changes
other than my one comment, rest looks good

2023-09-25 16:04 UTC, IgorTodorovskiIBM commented
This PR needs a bit of rework, will work on it this week

2023-11-08 02:18 UTC, IgorTodorovskiIBM commented
Will revisit this at a later point or if requested

2023-11-08 02:18 UTC, closed without merging