Handle pax install
ZOSOpenTools/meta pull request #552
Opened 2023-11-02 21:24 UTC by DevonianTeuchter

Handle installing direct from pax file;
- move "install" code from zopen-install into common.sh to enable creation of zopen-upgrade script [separation of concerns!] with appropriate parameters added/removed from each module
- refactoring monolithic "install" code [now in common.sh] into more specialized functions 
Numerous qol fixes found while smoke testing including: 
 - maintaining installation history so dependencies aren't checked multiple times (resolves #472  #431)
 - allowing an "a" option for the "_Do you want to continue (y/n/a)?_" question to automatically answer "yes" to any future questions [in case a command is run without -y/--yes and the user actually meant to!
 - performance when alternating/upgrading improved by diffing updated files rather than systematically checking all symlinks for existence [still required for removal]; resolve #533 as much as possible [removal processing will always be slow due to the need to check every possible file a package ships to see if that symlink is still active]
 - improving query of installed packages
 - improving screen formatting calculation using screen cols (resolve #468)
 - make install less noisier still  (resolve #381)
 - resolve #253 

A global configuration for a paxfile repository [currently a single directory] can be set during initialization using the `--paxrepodir <dir>` option. This can be manually adjusted in the global config at <ZOPEN_ROOTFS>/etc/zopen/paxrepodir. ` --paxrepodir` can also be used with `zopen install ` to force a lookup of that repo for the specified package/pax.

Paxes can be installed using the command:
`zopen install --paxinstall path/to/<paxfile.pax.Z>`   - installs pax as found at specified location
`zopen install --paxinstall <package>`   - attempts to locate a pax for package in the current direcotry or in the global paxrepodir if configured
`zopen install --paxinstall --paxrepodir <dir> <package>.pax.Z` - install the specified package pax file, looking in <dir> for the file

Note that the manual has not been updated - the code is semi-"dark-shipped" for those able to test while the normal installation methodology continues as normal.  Once stabilised, the official documentation can be updated.

2023-11-02 22:17 UTC, MikeFultonDev requested changes
Please add some tests to the framework and ensure no regressions on existing tests before we merge

2023-11-03 13:48 UTC, IgorTodorovskiIBM commented
/run tests

2023-11-03 16:52 UTC, IgorTodorovskiIBM commented on bin/zopen-init
> +      --paxrepodir <RPEO>
duplicate flags? Also, RPEO -> REPO

2023-11-03 16:56 UTC, IgorTodorovskiIBM commented
I'm seeing some changes that are probably not intended. 
You may need to do a git rebase --interactive to remove some of the commits not intended in this PR (like this https://stackoverflow.com/questions/36168839/how-to-remove-commits-from-a-pull-request)

2023-11-14 20:10 UTC, DevonianTeuchter commented
Additional testing added under https://github.com/ZOSOpenTools/metaport/pull/28

2023-11-14 20:11 UTC, DevonianTeuchter commented
/run tests

2023-11-18 18:38 UTC, DevonianTeuchter commented
/run tests

2023-11-21 22:53 UTC, DevonianTeuchter commented
Should also resolve: https://github.com/ZOSOpenTools/metaport/issues/23

2024-01-17 01:57 UTC, MikeFultonDev approved these changes
did not mean to approve - ignore.

2024-01-17 02:00 UTC, MikeFultonDev reviewed
Hm. just a draft. ignore my approval 😁

2024-03-23 13:56 UTC, closed without merging