Fix date to timestamp conversion
ZOSOpenTools/meta pull request #649
Opened 2024-01-03 15:24 UTC by IgorTodorovskiIBM

* Fixes the issue in processAnalyticsFromLogFile as reported by @AnthonyGiorgio by embedding date into utilities:
```
parse error: Invalid numeric literal at line 1, column 10
FSUM9364 Bad date conversion: 2023-10-06 10:42:29
Usage: date [-cu] [-d time] [+format]
```
* Also embeds sha256sum, which would be used to verify the checksum matches the metadata.json's checksum

**Note:**
Another approach would be to embed coreutils (which includes date, sha256sum and many other tools). Another benefit of this is that we don't have to rely ascii workarounds like asciiecho (https://github.com/ZOSOpenTools/meta/blob/main/bin/zopen-build#L40) and we also can replace [numcpus.rexx](https://github.com/ZOSOpenTools/meta/blob/main/bin/numcpus.rexx) with `nproc`. It will increase size by 14mbs though.

2024-01-05 15:19 UTC, HarithaIBM approved these changes

2024-01-05 21:30 UTC, AnthonyGiorgio requested changes

2024-01-05 21:30 UTC, AnthonyGiorgio commented on include/analytics.sh
> +    set -x
Is this for debugging?

2024-01-12 17:39 UTC, IgorTodorovskiIBM commented on include/analytics.sh
> +    set -x
yep, removed it, thanks

2024-01-17 01:44 UTC, MikeFultonDev approved these changes
This is fine but can you create another issue so that we can pick up fixes to date/sha256sum if they are required as part of the build process of meta?

2024-01-17 02:45 UTC, IgorTodorovskiIBM commented
> This is fine but can you create another issue so that we can pick up fixes to date/sha256sum if they are required as part of the build process of meta?

Will do

2024-01-17 02:45 UTC, merged